### ISSUE TITLE
Option to choose buildType

### ISSUE THREAD

**Issue by Plinzen** [xmartlabs/android-snapshot-publisher#29]
Hello, 

thanks for your contribution on this plugin. However I have a question regarding `buildType`: As far as I understood currently only the release buildType is used. Can this be configured to e.g. use `debug` or a different buildType?

Thanks!

**Comment by matir91** [comment]
Hi! Thanks for asking, right now you can use all `buildTypes` that have [`debuggable`](http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html#com.android.build.gradle.internal.dsl.BuildType:debuggable) property in `false`. If you are trying to use the default `debug` build type, it's `debuggable`, so you won't be able to use it with this plugin.

The main reason why it's disabled, is you cannot deploy a `debuggable` apk in Google Play. However, I'm not sure about Fabric (I'll test it). Do you want to release a `debuggable` apk in Fabric? If that's right, why would you want to release a `debuggable` apk?

**Comment by Plinzen** [comment]
Hi Matías, 
thanks for your answer, indeed we want to publish to Fabric Beta instead of Google Play. 
We share our application to internal beta testers only. We have the debuggable flag enabled to allow the testers reading the logs. Since your app is just a little part of an overall system, we want to give our beta users / testers (which are also in fact sw engineers from different disciplines) the full abilities to see what's going on in the app. This includes access to logs for example. 
Maybe you can just ignore the debuggable flag for the Fabric related tasks?

**Comment by matir91** [comment]
yes, makes sense. The library was though to upload test builds, so we can include them!
